### ISSUE TITLE
Venue and Result information

### ISSUE THREAD

**Issue by pssguy** [tvganesh/cricketr#2]
Thanks for this package
I'm about to release an alpha version of a shiny dashboard based on it

Would it be possible to return venue and result data as columns in the getPlayerData() function

**Comment by tvganesh** [comment]
pssguy,
             The getPlayerData() does include the venue as column. Regarding the result if you use
wins <- getPlayerData(35230,dir=".,file="tendulkar.csv",homeOrAway=c(1,2),result=c(1))

it would create a data.frame for the player of all innings in which the team won
and
lostDrawn<-  getPlayerData(35230,dir=".,file="tendulkar.csv",homeOrAway=c(1,2),result=c(2,4))
would result in a data frame of the player for all matches that were lost or drawn.

You could manipulate these data frames as you like by adding a column 'won' or 'lost' with status 1 or 0.  The data frame will include the ground in which the match was played and also the opposition team.

Please take a look at batsmanContributionWonLost.R where I create separate data frames for wins and losses.

You could do something similar. Let me know.
A Shiny package would be terrific.

Kindly  keep me posted about the release of  your Shiny package alpha version

Thanks
Ganesh

**Comment by pssguy** [comment]
Thanks for getting back so promptly
Re venue, I meant Home or Away rather than ground
Re result. Yep I know I could make calls for each result but with an interactive app time is of the essence . I kinda assumed that if you had homeoraway and result as parameters, you could return them in a data.frame but I'm not much of a coder

**Comment by pssguy** [comment]
Here is [shiny app Mark 1](https://mytinyshinys.shinyapps.io/cricket)

**Comment by tvganesh** [comment]
Andrew,
            Unfortunately ESPN Cricinfo does not provide home/away or result(win,draw,loss) directly. They have to obtained through separate calls. So if you want venue and result as columns there needs to be 4 different calls
1) home - win 2) home -loss/draw 3) away-win 4)away-loss/draw
I am tied up for the next 2 weeks. Will try to have the code if I can in-between
Took a look at your app. Eagerly awaiting  inclusion of other features

Regards
Ganesh
Ganesh

**Comment by pssguy** [comment]
Ganesh  Each call takes around 2s. I would need 3 to get win draw and loss separately . Venue is less important. I'll have to make a callI will do more cricket stuff but have a few other projects on the go as well and will update on twitter . Just wanted to try out your package Thanks again for doing itAndrew 

```
 On Wednesday, July 15, 2015 6:05 PM, Tinniam V Ganesh <notifications@github.com> wrote:
```

 Andrew,
 Unfortunately ESPN Cricinfo does not provide home/away or result(win,draw,loss) directly. They have to obtained through separate calls. So if you want venue and result as columns there needs to be 4 different calls
1) home - win 2) home -loss/draw 3) away-win 4)away-loss/draw
I am tied up for the next 2 weeks. Will try to have the code if I can in-between
Took a look at your app. Eagerly awaiting inclusion of other featuresRegards
Ganesh
Ganesh—

**Comment by tvganesh** [comment]
Andrew,
            Added a new function getPlayerDataSp() in the latest version 0.0.5 in which there are 2 columns as you requested
with the values as follows
ha ==> home=1, away=2
result ==> won=1,lost=2, drawn=4

Please take a look and let me know.

Regards
Ganesh

**Comment by pssguy** [comment]
Thanks  for this.
Looks good but appears much slower processing, so anything that can be done to address that would  be useful

```
 system.time(old <- getPlayerData(35320))
   user  system elapsed 
   0.50    0.01    4.05 
 system.time(new <- getPlayerDataSp(35320))
   user  system elapsed 
   0.79    0.21   19.01 
```

**Comment by tvganesh** [comment]
As I had earlier mentioned I had to make 6 calls to implement this function as it is not available readily from Cricinfo. It looks like Cricinfo has to look across tables to get this data.

One suggestion is that you obtain player data for common players and store locally. Use the local data to display your charts  and info, when the call is made, rather than fetching from ESPN each time, if you  have the data locally. Store data locally if URL call is made. Overtime you will have data for most players locally. This technique is commonly used in cloud systems

Will let you know if I think of something else.

Ganesh

**Comment by pssguy** [comment]
It's horses for courses. For detailed analyses, like your web entries, then  a local database would be appropriate. Even all players would not be that sizeable, I imagine; or take that long to set up. 
But for the dashboard approach, I want all the latest data so relying on an immediately outdated dataset is inappropriate
Thanks again, anyways
