### ISSUE TITLE
Is there a feature where we can get players data in reverse ( recent to old)

### ISSUE THREAD

**Issue by puneetloya** [tvganesh/cricketr#3]
Adding a parameter to the getPlayerData will work it out.

parameter orderbyad=forward in the URL gives you in chronological order and orderbyad=reverse gives in the reverse chronological order.

**Comment by tvganesh** [comment]
I don't understand? How many player's data are you thinking? Also I wouldn't want to write a function that overloads ESPN Cricinfo with a call with too many requests. You can however  write a loop and use the getPlayerData inside it.
