### ISSUE TITLE
Error Installing package

### ISSUE THREAD

**Issue by yogmangela** [tvganesh/cricketr#4]
Hi Ganesh,

![image](https://cloud.githubusercontent.com/assets/6623718/11473754/33e2fb62-976c-11e5-9151-b7f4e9473e50.png)

I get above error while installing package in R.

Any thought?

> library(devtools)
> install_github("tvganesh/cricketr")
> Downloading GitHub repo tvganesh/cricketr@master
> Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
>   there is no package called ‘stringi’

Thanks,
Yogs

**Comment by tvganesh** [comment]
Yog - I just tried and I don't get the error.  Will try to check. Maybe you should try rm(list=ls()) and then try again.

Regards
Ganesh

**Comment by yogmangela** [comment]
I tried that too,
sorry getting same error. 
what is "there is no package called ‘stringi’"

**Comment by yogmangela** [comment]
no worries, I've solved it, Successfully installed your package. had to run> update.packages()

**Comment by tvganesh** [comment]
Cool. What was the problem?

**Comment by yogmangela** [comment]
Well I think it needed package called "stringi". and I to update all the other packages.

Here is the link I followed: http://stackoverflow.com/questions/30173752/newer-version-of-r-does-not-load-older-packages

**Comment by tvganesh** [comment]
Ok. Good.
